#!/bin/bash
#read -p "Enter case folder name:  " ${case}
# "case" is the place workdir directory in a sence.

read -p "!! Enter machine: 1) Turbule (McGill computer); computer 2) Bepsi (personal computer); 3) Beluga (Compute Canada)" pcid
#read pcid
if [ "${pcid}" == "1" ] 
then
    machine_name=Turbule
    lapack_path=/usr/lib64/
    fishpack_path=/aos/home/celizotte/fishpack-master/lib
    model_path=~/Desktop/Modele-shallow-water-multicouches
    compiler="gfortran"
    opt="-L/usr/lib -lblas -llapack  -L$fishpack_path -lfishpack -I$fishpack_path"
    main=$model_path/main2.f90
    # casefile
    case=~/Desktop/Modele-shallow-water-multicouches/newcase
    
elif [ "${pcid}" == "2" ]
then
    machine_name=Bepsi
    model_path=/home/charlesedouard/Desktop/Travail/modelSW
    lapack_path=/usr/lib/x86_64-linux-gnu/lapack
    fishpack_path=/home/charlesedouard/Desktop/Travail/fishpack/lib
    #compiler="gfortran"
    compiler="mpifort"
    opt="-L/usr/lib -lblas -llapack  -L$fishpack_path -lfishpack -I$fishpack_path"
    main=$model_path/main.f90
    # casefile
    case=newcase
elif [ "${pcid}" == "3" ]
then    
    # BLAS and LAPACK
    module load openblas
    module load flexiblas

    # Compiler options
    machine_name=Beluga
    model_path=$HOME/projects/def-lpnadeau/celiz2/modelSW
    fishpack_path=$HOME/projects/def-lpnadeau/celiz2/fishpack-master/lib
    compiler="mpifort"
    module load gcc
    module load openmpi
    opt="-fbacktrace -Wall -fcheck=all -lflexiblas  -L$fishpack_path -lfishpack -I$fishpack_path"
    main=$model_path/main.f90
    # casefile
    case=newcase
fi

# >>> Preparing before compilation ::
echo "!! Using setting for ${machine_name} with fishpack stored at ${fishpack_path} and lapack at ${lapack_path}"
#cp "${model_path}/parameters.f90" "${case}/."
echo "!! Parameters file copied from ${model_path} to ${case}"

# >>> Compilation ::
$compiler -O3 -o  $case/exec $main $opt
#mpif90 -O3 -o  $case/exec $model_path/main.f90  -L/usr/lib -lblas -llapack  -L$fishpack_path -lfishpack -I$fishpack_path



# >>> Parameter last compiled in model directory ::
cp ${model_path}/parameters.f90 ${model_path}/parameters.f90_last_compiled

# >>> Parameter last compiled in compiled directories :: 
cp ${model_path}/parameters.f90 ${case}/parameters.f90_last_compiled

# >>> Ending ::
echo "!! Compilation of $case/exec completed on the computer $machine_name."
