#!/bin/bash

model_path=~/Desktop/Modele-shallow-water-multicouches
workdir=/storage/celizotte/work_Nlayers_test
read -p "How would you name the work file?" casename
case_dir=$workdir/$casename
echo "Creating directory ${case_dir}".
rm -r $case_dir 2> /dev/null
cp -r $model_path/newcase $case_dir

