#!/bin/bash
#mudpack_path=/usr/lib/x86_64-linux-gnu/mudpack
mudpack_path=~/mudpack5.0.1/lib
#lapack_path=/usr/lib/x86_64-linux-gnu/lapack
lapack_path=/usr/lib64
blas_path=/usr/lib64
testfile=mudpack-test.f90
#testfile=tmud2.f
gfortran -o  poisson-exec $testfile -L$mudpack_path -lmudpack -L$lapack_path -llapack
#gfortran -o  poisson-exec $testfile -L$mudpack_path -lmudpack
